### ISSUE TITLE
variable 'dummy' set but not used 

### ISSUE THREAD

**Issue by kjmeagher** [icecube/photospline#32]
I am getting a lot of warnings like this from code that uses photo spline. It looks like dummy is only being used on certain code paths
```
/usr/local/include/photospline/detail/bspline_eval.h:590:18: warning: variable 'dummy' set but not used [-Wunused-but-set-variable]
        volatile double dummy;
```

**Comment by cnweaver** [comment]
The variable is always used, and the compiler warning is arguably wrong-ish, but see if the change in https://github.com/icecube/photospline/pull/33 cleans this up for you.

**Comment by kjmeagher** [comment]
That solution removes the warning, but I don't see why the warning is wrong, dummy is never accessed

**Comment by cnweaver** [comment]
The value is never _loaded_ (since the variable is defined locally it cannot be used from elsewhere and cannot be something memory mapped) but the variable is used as a sink to ensure that the result of the calculations being benchmarked cannot be optimized away, as removing writes to volatile variables is forbidden. So, the compiler is trying to be helpful about identifying dead code, but does not actually understand the context, so while the warning is technically correct (up to poor wording), it is not useful.

**Comment by cnweaver** [comment]
Fixed by https://github.com/icecube/photospline/pull/33

**Comment by cnweaver** [comment]
Fixed by https://github.com/icecube/photospline/pull/33
